"""Render every game tile to a PNG and build a visual reference doc.

    python -m tools.dump_tiles

Writes docs/tiles/tile_XX.png (one per tile id) and docs/TILES.md — a table of all 256
tiles with their sprite, hex id, current name (from tiles.TILE_NAMES), and walkability.
Tiles we haven't named yet show "(unnamed — ?)"; fill those in and I'll fold the names
into tiles.py as constants. This is also the editor agent's map of "what tile is what".
"""
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ultima4.graphics import decode_shapes
from ultima4.savefile import load_bytes
from ultima4.tiles import TILE_NAMES, WALKABLE_ON_FOOT

TILE = 16
ZOOM = 3


def main() -> None:
    tiles = decode_shapes(load_bytes("SHAPES.EGA"))     # list of 16x16 RGB byte buffers
    docs = Path(__file__).resolve().parent.parent / "docs"
    img_dir = docs / "tiles"
    img_dir.mkdir(parents=True, exist_ok=True)

    # Render every sprite once.
    for i, buf in enumerate(tiles):
        img = Image.frombytes("RGB", (TILE, TILE), bytes(buf))
        img.resize((TILE * ZOOM, TILE * ZOOM), Image.NEAREST).save(img_dir / f"tile_{i:02X}.png")

    def cell(i: int) -> str:
        name = TILE_NAMES.get(i, "**?**")
        return f"![](tiles/tile_{i:02X}.png)<br>`{i:02X}` {name}"

    rows = ["# Ultima IV tile reference",
            "",
            "_Generated by `./run tiles` — do not edit by hand._  Names live in "
            "`ultima4/tiles.py` (`TILE_NAMES`). To rename a tile, use the **rename-tile** "
            "skill, e.g. `/rename-tile 0x4A -> stone_altar` (it updates the source, cascades "
            "animation-frame names, regenerates this file, and runs the tests).",
            "",
            f"All {len(tiles)} tiles from `SHAPES.EGA`, laid out as a grid so you can see "
            "them together (the hex id is each tile's `(row,col)` — row = high nibble, "
            "col = low nibble). Cells marked **?** still need a name.",
            ""]
    # 16-wide grid: one row per high nibble, mirroring a classic tile sheet.
    rows.append("| _ | +0 | +1 | +2 | +3 | +4 | +5 | +6 | +7 | +8 | +9 | +A | +B | +C | +D | +E | +F |")
    rows.append("|" + "---|" * 17)
    for hi in range(0, len(tiles), 16):
        line = [f"**{hi:02X}**"] + [cell(hi + lo) for lo in range(16)]
        rows.append("| " + " | ".join(line) + " |")

    named = sum(1 for i in range(len(tiles)) if i in TILE_NAMES)
    rows += ["",
             f"**{named}/{len(tiles)} named, {len(tiles) - named} still need names.** "
             "Walkable-on-foot tiles (for reference): "
             + ", ".join(f"`{t:02X}`" for t in sorted(WALKABLE_ON_FOOT)) + "."]

    (docs / "TILES.md").write_text("\n".join(rows) + "\n", encoding="utf-8")
    named = sum(1 for i in range(len(tiles)) if i in TILE_NAMES)
    print(f"Wrote {docs/'TILES.md'} and {len(tiles)} sprites to {img_dir}")
    print(f"{named}/{len(tiles)} tiles named; {len(tiles) - named} still need names.")


if __name__ == "__main__":
    main()
