"""Generate the agent reference tables into docs/AGENTS.md — `./run reference`.

Agents were burning tokens re-deriving facts the game already knows (the moongate schedule, town
coordinates, the recruit rule). This emits those as tables agents can cite. Generated FROM
`data_tables.py` (+ the `_join` rule) so they can't silently drift when someone "adds a moongate"
or moves a town. Regenerate after changing those tables.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ultima4.data_tables import (MOONGATE_X, MOONGATE_Y, PLACE_X, PLACE_Y,   # noqa: E402
                                 CLASS_NAMES, CLASS_COMPANION, CLASS_HOME)

BEGIN = "<!-- BEGIN generated reference tables (regenerate: ./run reference) -->"
END = "<!-- END generated reference tables -->"


def _moon_windows():
    """From a fresh game (cascade at 0,0), which Felucca phases each Trammel phase coexists with —
    i.e. which destinations a gate at each location can reach (C: +2 Trammel / +6 Felucca per bump)."""
    tc = fc = 0
    seen: dict = {}
    for _ in range(200):
        seen.setdefault(tc >> 5, set()).add(fc >> 5)
        tc = (tc + 2) & 0xFF
        fc = (fc + 6) & 0xFF
    return {tp: sorted(seen[tp]) for tp in range(8)}


def build() -> str:
    out = [BEGIN, "",
           "## Agent reference tables (generated — cite these, do not re-derive)", "",
           "_Generated by `./run reference` from `data_tables.py`; don't hand-edit._", ""]

    out += ["### Moongate schedule", "",
            "The open gate's **location** follows the current **Trammel** phase; stepping through it "
            "teleports you to the current **Felucca** phase's location (same `MOONGATE_X/Y` table). "
            "Felucca cycles ~3x faster, and the two are phase-locked, so **from a fresh game each gate "
            "location only reaches a fixed 3-destination window**:", "",
            "| Trammel phase | gate location (x,y) | reachable destinations `felucca:(x,y)` |",
            "|:-:|:-:|:--|"]
    win = _moon_windows()
    for tp in range(8):
        dests = ", ".join(f"{fp}:({MOONGATE_X[fp]},{MOONGATE_Y[fp]})" for fp in win[tp])
        out.append(f"| {tp} | ({MOONGATE_X[tp]},{MOONGATE_Y[tp]}) | {dests} |")
    out += ["",
            "**Directed travel:** `travel_to` a gate location, then `wait_until('moongate <x> <y>')` "
            "with the destination you want from the table above — it advances the clock until the open "
            "gate leads *there* (bare `wait_until('moongate')` only catches the FIRST of the 3, which "
            "usually isn't the one you want), then step onto the gate. A gate reaches exactly the 3 "
            "destinations in its row; targeting anything else times out and reports the reachable ones. "
            "`observe()['moons']` always carries the live phases + open gate.", ""]

    out += ["### Companions, home towns, and the join rule", "",
            f"Class index = virtue = home town. **Lord British's Castle (level-ups + healing): "
            f"({PLACE_X[0]},{PLACE_Y[0]}).**", "",
            "| class | companion | home town | town (x,y) |", "|:--|:--|:--|:-:|"]
    for ci in range(8):
        # a town's location id is class+5, so its PLACE_X/Y index is class+4
        out.append(f"| {ci} {CLASS_NAMES[ci]} | {CLASS_COMPANION[ci]} | {CLASS_HOME[ci]} | "
                   f"({PLACE_X[ci + 4]},{PLACE_Y[ci + 4]}) |")
    out += ["",
            "**Join rule** (C: `U4_TALK.C`; `dialogue.py _join`): a companion joins only if **their "
            "class ≠ the Avatar's own class** (a Fighter Avatar can never recruit Geoffrey the Fighter), "
            "**and** that virtue's karma ≥ 40 (or exactly 0), **and** `100·(party size) + 100 ≤ Avatar "
            "hp_max` — so level up at Lord British (he raises hp_max) to unlock party slots.", "", END]
    return "\n".join(out)


def main() -> None:
    doc = Path(__file__).resolve().parent.parent / "docs" / "AGENTS.md"
    text = doc.read_text(encoding="utf-8")
    section = build()
    if BEGIN in text and END in text:
        text = re.sub(re.escape(BEGIN) + ".*?" + re.escape(END), lambda _: section, text, flags=re.S)
    else:                                              # first run: place before the connection section
        anchor = "## How an external agent connects"
        text = (text.replace(anchor, section + "\n\n" + anchor, 1) if anchor in text
                else text.rstrip() + "\n\n" + section + "\n")
    doc.write_text(text, encoding="utf-8")
    print(f"wrote reference tables to {doc}")


if __name__ == "__main__":
    main()
